import type { UIMessage } from 'ai'
import { ref } from 'vue'

import { exportDTCG, selectionToJSX } from '@redrob-design/core/design-jsx'
import type { SceneGraph } from '@redrob-design/scene-graph'

import { reviewPage } from '@/app/review/findings'
import { demoMode } from '@/app/runtime/demo'

/** Bumped by the Ship button; the open thread posts the ship message. */
export const shipRequest = ref(0)

export function requestShip(): void {
  shipRequest.value++
}

/** What a ship message carries: how much is still open when the person ships. */
export interface ShipData {
  pageId: string
  openFindings: number
  frameCount: number
}

export function isShipData(value: unknown): value is ShipData {
  return (
    typeof value === 'object' &&
    value !== null &&
    'pageId' in value &&
    typeof value.pageId === 'string' &&
    'openFindings' in value &&
    typeof value.openFindings === 'number' &&
    'frameCount' in value &&
    typeof value.frameCount === 'number'
  )
}

export interface ShipWords {
  ready: string
  open: (count: number) => string
  empty: string
}

let shipCount = 0

/** Ship costs nothing and runs no AI: it is a check and the ways out. */
export function shipMessage(graph: SceneGraph, pageId: string, words: ShipWords): UIMessage {
  const review = reviewPage(graph, pageId)
  const data: ShipData = {
    pageId,
    openFindings: review.findings.length,
    frameCount: review.frameCount
  }
  let text = words.ready
  if (data.frameCount === 0) text = words.empty
  else if (data.openFindings > 0) text = words.open(data.openFindings)
  return {
    id: `ship-${Date.now()}-${++shipCount}`,
    role: 'assistant',
    parts: [
      { type: 'text', text },
      { type: 'data-ship', data }
    ]
  }
}

export function hasShipMessage(messages: readonly UIMessage[]): boolean {
  return messages.some((message) => message.parts.some((part) => part.type === 'data-ship'))
}

/** The page's frames as one React + Tailwind file and its tokens, ready to download. */
export function reactAndTokens(graph: SceneGraph, pageId: string): { jsx: string; tokens: string } {
  const frames = graph.getChildren(pageId).filter((node) => node.visible)
  const body = selectionToJSX(
    frames.map((node) => node.id),
    graph,
    'tailwind'
  )
    .split('\n')
    .map((line) => (line ? `      ${line}` : line))
    .join('\n')
  const jsx = [
    '// Generated by Redrob Design. Colors and spacing read tokens.css or tokens.json.',
    'export default function Page() {',
    '  return (',
    '    <>',
    body,
    '    </>',
    '  )',
    '}',
    ''
  ].join('\n')
  return { jsx, tokens: `${JSON.stringify(exportDTCG(graph), null, 2)}\n` }
}

/**
 * Handing off needs a service that is not connected yet. On /demo it answers
 * the way the prototype does; elsewhere it says so. Publishing lives in
 * `./publish/service`.
 */
export type ShipStubResult = { connected: true; detail: string } | { connected: false }

export function handToClaudeCode(): ShipStubResult {
  return demoMode.value ? { connected: true, detail: 'MCP' } : { connected: false }
}
